# This is a config for E2B sandbox template.
# You can use template ID (syvvs1ijpd1dovri71y5) or template name (codegen-dev-v2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("codegen-dev-v2") # Sync sandbox
# sandbox = await AsyncSandbox.create("codegen-dev-v2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('codegen-dev-v2')

team_id = "97040773-f47a-4e5d-8350-fe47b06c3ecb"
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_name = "codegen-dev-v2"
template_id = "syvvs1ijpd1dovri71y5"
